# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observation_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19observation_message.proto\"\x83\x03\n\x12ObservationMessage\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\t\n\x01Z\x18\x03 \x01(\x02\x12\r\n\x05v_aex\x18\x04 \x01(\x02\x12\r\n\x05v_aey\x18\x05 \x01(\x02\x12\r\n\x05v_aez\x18\x06 \x01(\x02\x12\x0c\n\x04v_ex\x18\x07 \x01(\x02\x12\x0c\n\x04v_ey\x18\x08 \x01(\x02\x12\x0c\n\x04v_ez\x18\t \x01(\x02\x12\x0c\n\x04\x61_ex\x18\n \x01(\x02\x12\x0c\n\x04\x61_ey\x18\x0b \x01(\x02\x12\x0c\n\x04\x61_ez\x18\x0c \x01(\x02\x12\n\n\x02my\x18\r \x01(\x02\x12\r\n\x05gamma\x18\x0e \x01(\x02\x12\x0b\n\x03\x63hi\x18\x0f \x01(\x02\x12\r\n\x05\x61lpha\x18\x10 \x01(\x02\x12\x0c\n\x04\x62\x65ta\x18\x11 \x01(\x02\x12\x0b\n\x03v_x\x18\x12 \x01(\x02\x12\x0b\n\x03v_y\x18\x13 \x01(\x02\x12\x0b\n\x03v_z\x18\x14 \x01(\x02\x12\x0c\n\x04mach\x18\x15 \x01(\x02\x12\x0b\n\x03psi\x18\x16 \x01(\x02\x12\r\n\x05theta\x18\x17 \x01(\x02\x12\x0b\n\x03phi\x18\x18 \x01(\x02\x12\x0c\n\x04pdot\x18\x19 \x01(\x02\x12\x0c\n\x04qdot\x18\x1a \x01(\x02\x12\x0c\n\x04rdot\x18\x1b \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observation_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVATIONMESSAGE._serialized_start=30
  _OBSERVATIONMESSAGE._serialized_end=417
# @@protoc_insertion_point(module_scope)
